version: '3'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - server/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
    restart: on-failure

  haproxy:
    build:
      context: haproxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - haproxy/.env
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs
    depends_on:
      - server
    restart: on-failure

  certbot:
    build:
      context: certbot
      dockerfile: Dockerfile
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certs:/certs
    env_file:
      - certbot/.env
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    env_file:
      - mongodb/.env
    ports:
      - ${TAILSCALE_IP}:27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: on-failure
    command: mongod --auth

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local 
