version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 8765), timeout=1)"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s 