version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8765:8765"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
    restart: on-failure

  haproxy:
    image: haproxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - server
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certs:/certs
    command: >
      sh -c "
        while :; do
          if [ ! -f /etc/letsencrypt/live/$${DOMAIN}/fullchain.pem ]; then
            certbot certonly --standalone --agree-tos --no-eff-email --email admin@$${DOMAIN}
            -d $${DOMAIN} --non-interactive --keep-until-expiring &&
            cat /etc/letsencrypt/live/$${DOMAIN}/fullchain.pem
                /etc/letsencrypt/live/$${DOMAIN}/privkey.pem
                > /certs/haproxy.pem &&
            echo 'Certificate created successfully'
          else
            echo 'Certificate already exists, checking for renewal...'
            certbot renew --quiet &&
            cat /etc/letsencrypt/live/$${DOMAIN}/fullchain.pem
                /etc/letsencrypt/live/$${DOMAIN}/privkey.pem
                > /certs/haproxy.pem &&
            echo 'Certificate renewed successfully'
          fi
          sleep 12h
        done
      "
    ports:
      - "8080:80"
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: admin
    ports:
      - ${TAILSCALE_IP}:27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: on-failure
    command: mongod --auth

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local 