flutter_root = '/Users/romansmirnov/ios-dev/flutter'
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

platform :ios, '12.0'

# CocoaPods analytics sends network stats. Disable if you want.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!  # optional, but often needed for Swift pods

  # Add your pod dependencies here
  pod 'FirebaseCore', '~> 10.0'  # <-- dummy pod to force workspace creation

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end