import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../state/threads_state.dart';
import '../state/sequencer_state.dart';
import '../widgets/app_header_widget.dart';
import '../services/threads_service.dart';
import 'user_profile_screen.dart';

class CheckpointsScreen extends StatefulWidget {
  final String threadId;
  
  const CheckpointsScreen({
    super.key,
    required this.threadId,
  });

  @override
  State<CheckpointsScreen> createState() => _CheckpointsScreenState();
}

class _CheckpointsScreenState extends State<CheckpointsScreen> {
  final ScrollController _scrollController = ScrollController();

  // Chat layout configuration - easily adjustable percentages
  static const double _currentUserLeftMarginPercent = 0.25;   // 25% margin on left for current user messages
  static const double _otherUserRightMarginPercent = 0.25;    // 25% margin on right for other user messages
  static const double _messageMaxWidthPercent = 0.7;         // 70% max width for message bubbles
  static const double _baseMarginPercent = 0.02;             // 2% base margin (minimum spacing)

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _refreshThreadData();
      _scrollToBottom();
    });
  }

  Future<void> _refreshThreadData() async {
    try {
      final threadsState = context.read<ThreadsState>();
      
      // Fetch latest thread data from server
      final latestThread = await ThreadsService.getThread(widget.threadId);
      if (latestThread != null) {
        // Update the current thread in ThreadsState with fresh data
        threadsState.setActiveThread(latestThread);
        debugPrint('✅ Refreshed thread data: ${latestThread.checkpoints.length} checkpoints');
      }
    } catch (e) {
      debugPrint('⚠️ Failed to refresh thread data: $e');
    }
  }

  void _scrollToBottom() {
    if (_scrollController.hasClients) {
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeOut,
      );
    }
  }

  void _showProjectInfo() {
    final threadsState = context.read<ThreadsState>();
    final thread = threadsState.currentThread;
    
    if (thread == null) return;
    
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(thread.title),
        content: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Created: ${thread.createdAt.toString().substring(0, 16)}'),
            Text('Last updated: ${thread.updatedAt.toString().substring(0, 16)}'),
            Text('Status: ${thread.status.name}'),
            const SizedBox(height: 16),
            const Text('Collaborators:', style: TextStyle(fontWeight: FontWeight.bold)),
            ...thread.users.map((user) => Padding(
              padding: const EdgeInsets.only(left: 16, top: 4),
              child: Text('• ${user.name}'),
            )),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  void _playCheckpointRender(ThreadCheckpoint checkpoint) {
    // Check if there are any renders available
    if (checkpoint.snapshot.audio.renders.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('No audio renders available for this checkpoint'),
          backgroundColor: Colors.orange,
          duration: Duration(seconds: 2),
        ),
      );
      return;
    }

    // Get the latest render
    final latestRender = checkpoint.snapshot.audio.renders.last;
    
    // Show a message that playback would start (placeholder for actual audio playback)
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Playing render: ${latestRender.url ?? 'Latest render'}'),
        backgroundColor: const Color(0xFF10B981),
        duration: const Duration(seconds: 2),
      ),
    );
    
    // TODO: Implement actual audio playback
    // This would typically involve:
    // 1. Loading the audio file from the render URL
    // 2. Using an audio player package like audioplayers
    // 3. Starting playback
    
    debugPrint('🎵 Playing checkpoint render: ${latestRender.url}');
  }

  bool _isUserComment(String comment) {
    // Filter out auto-generated comments
    final autoGeneratedPatterns = [
      'Published from mobile app',
      'Created project',
      'Started collaboration',
      'Started working on sequencer project',
    ];
    
    // Check if comment matches auto-generated patterns
    for (final pattern in autoGeneratedPatterns) {
      if (comment.contains(pattern)) {
        return false;
      }
    }
    
    // Filter out timestamp-based comments (like "update 28/06/2025 14:00")
    final timestampPattern = RegExp(r'^update \d{1,2}/\d{1,2}/\d{4} \d{1,2}:\d{2}$', caseSensitive: false);
    if (timestampPattern.hasMatch(comment.trim())) {
      return false;
    }
    
    // Filter out very short generic comments
    if (comment.trim().length < 3) {
      return false;
    }
    
    return true; // Show meaningful user comments
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppHeaderWidget(
        mode: HeaderMode.checkpoints,
        title: 'Project Checkpoints',
        onInfo: _showProjectInfo,
        showProjectInfo: true,
      ),
      backgroundColor: const Color(0xFF0f172a),
      body: Consumer2<ThreadsState, SequencerState>(
        builder: (context, threadsState, sequencerState, child) {
          final thread = threadsState.currentThread;
          
          if (thread == null) {
            return const Center(
              child: Text(
                'Project not found',
                style: TextStyle(color: Colors.white70),
              ),
            );
          }

          if (thread.checkpoints.isEmpty) {
            return const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(
                    Icons.history,
                    size: 64,
                    color: Colors.grey,
                  ),
                  SizedBox(height: 16),
                  Text(
                    'No checkpoints yet',
                    style: TextStyle(
                      color: Colors.grey,
                      fontSize: 18,
                    ),
                  ),
                  SizedBox(height: 8),
                  Text(
                    'Save your progress to create checkpoints',
                    style: TextStyle(
                      color: Colors.grey,
                      fontSize: 14,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            );
          }

          return Column(
            children: [
              Expanded(
                child: ListView.builder(
                  controller: _scrollController,
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  itemCount: thread.checkpoints.length,
                  itemBuilder: (context, index) {
                    final checkpoint = thread.checkpoints[index];
                    final isCurrentUser = checkpoint.userId == threadsState.currentUserId;
                    
                    return _buildCheckpointMessage(
                      context,
                      checkpoint,
                      isCurrentUser,
                      sequencerState,
                      threadsState,
                    );
                  },
                ),
              ),
              _buildNewCheckpointButton(context, threadsState, sequencerState),
            ],
          );
        },
      ),
    );
  }

  Widget _buildCheckpointMessage(
    BuildContext context,
    ThreadCheckpoint checkpoint,
    bool isCurrentUser,
    SequencerState sequencerState,
    ThreadsState threadsState,
  ) {
    final screenWidth = MediaQuery.of(context).size.width;
    
    return Container(
      margin: EdgeInsets.only(
        left: isCurrentUser 
            ? screenWidth * _currentUserLeftMarginPercent 
            : screenWidth * _baseMarginPercent,
        right: isCurrentUser 
            ? screenWidth * _baseMarginPercent 
            : screenWidth * _otherUserRightMarginPercent,
        top: 4.0,
        bottom: 4.0,
      ),
      child: Row(
        mainAxisAlignment: isCurrentUser ? MainAxisAlignment.end : MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (!isCurrentUser) ...[
            _buildUserAvatar(checkpoint.userName),
            const SizedBox(width: 8),
          ],
          Flexible(
            child: Container(
              constraints: BoxConstraints(
                maxWidth: screenWidth * _messageMaxWidthPercent,
              ),
              child: Column(
                crossAxisAlignment: isCurrentUser ? CrossAxisAlignment.end : CrossAxisAlignment.start,
                children: [
                  if (!isCurrentUser)
                    Padding(
                      padding: const EdgeInsets.only(left: 12, bottom: 4),
                      child: Text(
                        checkpoint.userName,
                        style: TextStyle(
                          color: _getUserColor(checkpoint.userName),
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  GestureDetector(
                    onTap: () => _applyCheckpoint(context, checkpoint, sequencerState),
                    child: Container(
                      decoration: BoxDecoration(
                        color: isCurrentUser 
                            ? const Color(0xFF0084ff) 
                            : const Color(0xFF374151),
                        borderRadius: BorderRadius.circular(18),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.1),
                            blurRadius: 4,
                            offset: const Offset(0, 2),
                          ),
                        ],
                      ),
                      padding: const EdgeInsets.all(12),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // Removed checkpoint title display - checkpoints now show only preview and timestamp
                          
                          const SizedBox(height: 4),
                          
                          // Sound grid preview
                          _buildSoundGridPreview(checkpoint.snapshot),
                          
                          const SizedBox(height: 8),
                          
                          // Media controls and info
                          Container(
                            padding: const EdgeInsets.all(8),
                            decoration: BoxDecoration(
                              color: Colors.black.withOpacity(0.2),
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Row(
                              children: [
                                // Play button for latest render
                                GestureDetector(
                                  onTap: () => _playCheckpointRender(checkpoint),
                                  child: Container(
                                    width: 32,
                                    height: 32,
                                    decoration: BoxDecoration(
                                      color: const Color(0xFF10B981),
                                      borderRadius: BorderRadius.circular(16),
                                    ),
                                    child: const Icon(
                                      Icons.play_arrow,
                                      color: Colors.white,
                                      size: 20,
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 12),
                                
                                // Duration info
                                const Icon(
                                  Icons.schedule,
                                  size: 14,
                                  color: Colors.white60,
                                ),
                                const SizedBox(width: 4),
                                Text(
                                  _formatDuration(checkpoint.snapshot.audio.duration),
                                  style: const TextStyle(
                                    color: Colors.white60,
                                    fontSize: 12,
                                  ),
                                ),
                                
                                const Spacer(),
                                
                                // Renders count (if any)
                                if (checkpoint.snapshot.audio.renders.isNotEmpty) ...[
                                  const Icon(
                                    Icons.audiotrack,
                                    size: 14,
                                    color: Colors.white60,
                                  ),
                                  const SizedBox(width: 4),
                                  Text(
                                    '${checkpoint.snapshot.audio.renders.length} renders',
                                    style: const TextStyle(
                                      color: Colors.white60,
                                      fontSize: 12,
                                    ),
                                  ),
                                ],
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  
                  // Timestamp
                  Padding(
                    padding: const EdgeInsets.only(top: 4),
                    child: Text(
                      _formatTimestamp(checkpoint.timestamp),
                      style: TextStyle(
                        color: Colors.grey[400],
                        fontSize: 11,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
          if (isCurrentUser) ...[
            const SizedBox(width: 8),
            _buildUserAvatar(checkpoint.userName),
          ],
        ],
      ),
    );
  }

  Widget _buildUserAvatar(String userName) {
    return Container(
      width: 32,
      height: 32,
      decoration: BoxDecoration(
        color: _getUserColor(userName),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Center(
        child: Text(
          userName.isNotEmpty ? userName[0].toUpperCase() : '?',
          style: const TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
            fontSize: 14,
          ),
        ),
      ),
    );
  }

  Widget _buildSoundGridPreview(SequencerSnapshot snapshot) {
    if (snapshot.audio.sources.isEmpty || 
        snapshot.audio.sources.first.scenes.isEmpty ||
        snapshot.audio.sources.first.scenes.first.layers.isEmpty) {
      return Container(
        height: 80,
        decoration: BoxDecoration(
          color: Colors.black.withOpacity(0.3),
          borderRadius: BorderRadius.circular(8),
        ),
        child: const Center(
          child: Text(
            'Empty Project',
            style: TextStyle(
              color: Colors.white60,
              fontSize: 12,
            ),
          ),
        ),
      );
    }

    final scene = snapshot.audio.sources.first.scenes.first;
    final layers = scene.layers;
    
    return Container(
      height: 80,
      decoration: BoxDecoration(
        color: Colors.black.withOpacity(0.3),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Padding(
        padding: const EdgeInsets.all(8),
        child: Column(
          children: [
            Text(
              'Sound Grid Preview',
              style: TextStyle(
                color: Colors.white.withOpacity(0.7),
                fontSize: 10,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 4),
            Expanded(
              child: Row(
                children: List.generate(
                  layers.length.clamp(0, 4), // Show max 4 layers
                  (layerIndex) {
                    final layer = layers[layerIndex];
                    return Expanded(
                      child: Container(
                        margin: const EdgeInsets.symmetric(horizontal: 1),
                        decoration: BoxDecoration(
                          color: _getLayerColor(layerIndex),
                          borderRadius: BorderRadius.circular(2),
                        ),
                        child: Column(
                          children: List.generate(
                            layer.rows.length.clamp(0, 8), // Show max 8 rows
                            (rowIndex) {
                              final row = layer.rows[rowIndex];
                              final hasSample = row.cells.any(
                                (cell) => cell.sample?.hasSample == true,
                              );
                              return Expanded(
                                child: Container(
                                  margin: const EdgeInsets.all(0.5),
                                  decoration: BoxDecoration(
                                    color: hasSample 
                                        ? Colors.white.withOpacity(0.8)
                                        : Colors.white.withOpacity(0.2),
                                    borderRadius: BorderRadius.circular(1),
                                  ),
                                ),
                              );
                            },
                          ),
                        ),
                      ),
                    );
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildNewCheckpointButton(
    BuildContext context,
    ThreadsState threadsState,
    SequencerState sequencerState,
  ) {
    return Container(
      padding: const EdgeInsets.all(16),
      child: Row(
        children: [
          Expanded(
            child: ElevatedButton.icon(
              onPressed: () => _createNewCheckpoint(context, threadsState, sequencerState),
              icon: const Icon(Icons.add_circle_outline),
              label: const Text('Save Checkpoint'),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF10b981),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 12),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(25),
                ),
              ),
            ),
          ),
          const SizedBox(width: 12),
          FloatingActionButton(
            onPressed: () => Navigator.of(context).pop(),
            backgroundColor: const Color(0xFF374151),
            child: const Icon(Icons.close),
          ),
        ],
      ),
    );
  }

  Color _getUserColor(String userName) {
    final colors = [
      const Color(0xFF10b981), // Green
      const Color(0xFF3b82f6), // Blue
      const Color(0xFFf59e0b), // Orange
      const Color(0xFFef4444), // Red
      const Color(0xFF8b5cf6), // Purple
      const Color(0xFF06b6d4), // Cyan
      const Color(0xFFf97316), // Orange
      const Color(0xFFec4899), // Pink
    ];
    
    final hash = userName.hashCode;
    return colors[hash.abs() % colors.length];
  }

  Color _getLayerColor(int layerIndex) {
    final colors = [
      const Color(0xFF3b82f6),
      const Color(0xFF10b981),
      const Color(0xFFf59e0b),
      const Color(0xFFef4444),
    ];
    return colors[layerIndex % colors.length];
  }

  String _formatTimestamp(DateTime timestamp) {
    final now = DateTime.now();
    final difference = now.difference(timestamp);
    
    if (difference.inDays > 0) {
      return '${difference.inDays}d ago';
    } else if (difference.inHours > 0) {
      return '${difference.inHours}h ago';
    } else if (difference.inMinutes > 0) {
      return '${difference.inMinutes}m ago';
    } else {
      return 'Just now';
    }
  }

  String _formatDuration(double duration) {
    final minutes = (duration / 60).floor();
    final seconds = (duration % 60).floor();
    return '${minutes}:${seconds.toString().padLeft(2, '0')}';
  }

  void _applyCheckpoint(
    BuildContext context,
    ThreadCheckpoint checkpoint,
    SequencerState sequencerState,
  ) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF374151),
        title: const Text(
          'Apply Checkpoint',
          style: TextStyle(color: Colors.white),
        ),
        content: Text(
          'This will replace your current project with this checkpoint.\n\nYour current work will be lost unless saved.',
          style: const TextStyle(color: Colors.white70),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () {
              sequencerState.applySnapshot(checkpoint.snapshot);
              Navigator.of(context).pop();
              Navigator.of(context).pop(); // Go back to sequencer
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: const Text('Applied checkpoint successfully'),
                  backgroundColor: const Color(0xFF10b981),
                ),
              );
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF10b981),
            ),
            child: const Text('Apply'),
          ),
        ],
      ),
    );
  }

  void _createNewCheckpoint(
    BuildContext context,
    ThreadsState threadsState,
    SequencerState sequencerState,
  ) {
    final commentController = TextEditingController();
    
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF374151),
        title: const Text(
          'Save Checkpoint',
          style: TextStyle(color: Colors.white),
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Add a comment to describe your changes:',
              style: TextStyle(color: Colors.white70),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: commentController,
              style: const TextStyle(color: Colors.white),
              decoration: const InputDecoration(
                hintText: 'e.g., Added bassline and drums',
                hintStyle: TextStyle(color: Colors.white54),
                border: OutlineInputBorder(),
                focusedBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Color(0xFF10b981)),
                ),
              ),
              maxLines: 3,
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              final comment = commentController.text.trim();
              if (comment.isEmpty) return;
              
              try {
                await threadsState.addCheckpointFromSequencer(
                  widget.threadId,
                  comment,
                  sequencerState,
                );
                
                Navigator.of(context).pop();
                
                // Scroll to bottom to show new checkpoint
                WidgetsBinding.instance.addPostFrameCallback((_) {
                  _scrollToBottom();
                });
                
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Checkpoint saved successfully!'),
                    backgroundColor: Color(0xFF10b981),
                  ),
                );
              } catch (e) {
                Navigator.of(context).pop();
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text('Failed to save checkpoint: $e'),
                    backgroundColor: Colors.red,
                  ),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF10b981),
            ),
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }
}

// Enhanced version that shows user context and common threads
class CheckpointsScreenWithUserContext extends StatefulWidget {
  final String threadId;
  final String targetUserId;
  final String targetUserName;
  final List<Thread> commonThreads;
  
  const CheckpointsScreenWithUserContext({
    super.key,
    required this.threadId,
    required this.targetUserId,
    required this.targetUserName,
    required this.commonThreads,
  });

  @override
  State<CheckpointsScreenWithUserContext> createState() => _CheckpointsScreenWithUserContextState();
}

class _CheckpointsScreenWithUserContextState extends State<CheckpointsScreenWithUserContext> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0f172a),
      body: Column(
        children: [
          // User header with threads button
          _buildUserHeader(),
          
          // Common threads pinned section (if more than 1 common thread)
          if (widget.commonThreads.length > 1)
            _buildCommonThreadsSection(),
          
          // Checkpoints content
          Expanded(
            child: CheckpointsScreen(threadId: widget.threadId),
          ),
        ],
      ),
    );
  }
  
  Widget _buildUserHeader() {
    return Container(
      padding: const EdgeInsets.fromLTRB(16, 50, 16, 12),
      decoration: const BoxDecoration(
        color: Color(0xFF374151),
        border: Border(
          bottom: BorderSide(color: Color(0xFFE5E7EB), width: 1),
        ),
      ),
      child: Row(
        children: [
          // Back button
          IconButton(
            icon: const Icon(Icons.arrow_back, color: Colors.white),
            onPressed: () => Navigator.pop(context),
          ),
          
          // User name with online indicator
          Expanded(
            child: Row(
              children: [
                Text(
                  widget.targetUserName,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(width: 8),
                // Online indicator (assuming online for now - you can connect this to actual user status)
                Container(
                  width: 8,
                  height: 8,
                  decoration: const BoxDecoration(
                    color: Color.fromARGB(255, 118, 41, 195),
                    shape: BoxShape.circle,
                  ),
                ),
              ],
            ),
          ),
          
          // Threads button
          ElevatedButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => UserProfileScreen(
                    userId: widget.targetUserId,
                    userName: widget.targetUserName,
                  ),
                ),
              );
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color.fromARGB(255, 118, 41, 195),
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              minimumSize: const Size(0, 36),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(6),
              ),
            ),
            child: const Text(
              'Profile',
              style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
            ),
          ),
        ],
      ),
    );
  }
  
  Widget _buildCommonThreadsSection() {
    // Filter out the current thread from common threads
    final otherCommonThreads = widget.commonThreads
        .where((thread) => thread.id != widget.threadId)
        .toList();
    
    if (otherCommonThreads.isEmpty) return const SizedBox();
    
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: Color(0xFF1e293b),
        border: Border(
          bottom: BorderSide(color: Color(0xFFE5E7EB), width: 1),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            '📌 Other Common Threads',
            style: TextStyle(
              color: Colors.white,
              fontSize: 14,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 8),
          ...otherCommonThreads.map((thread) => _buildPinnedThread(thread)),
        ],
      ),
    );
  }
  
  Widget _buildPinnedThread(Thread thread) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFF374151),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        children: [
          const Icon(Icons.push_pin, color: Colors.white70, size: 16),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              thread.title,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 14,
              ),
            ),
          ),
          TextButton(
            onPressed: () {
              // Switch to this thread
              final threadsState = Provider.of<ThreadsState>(context, listen: false);
              threadsState.setActiveThread(thread);
              
              Navigator.pushReplacement(
                context,
                MaterialPageRoute(
                  builder: (context) => CheckpointsScreenWithUserContext(
                    threadId: thread.id,
                    targetUserId: widget.targetUserId,
                    targetUserName: widget.targetUserName,
                    commonThreads: widget.commonThreads,
                  ),
                ),
              );
            },
            child: const Text(
              'Open',
              style: TextStyle(color: Color.fromARGB(255, 118, 41, 195)),
            ),
          ),
        ],
      ),
    );
  }
} 