name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

env:
  REPO_DIR_PATH: /home/luddite478/niyya

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Deploy to ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test available secrets
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Available secrets (names only):"
          echo '${{ toJSON(secrets) }}' | jq -r 'keys[]' | sort
          echo "---"
          echo "Checking specific secrets:"
          echo "HOST_IP exists: ${{ secrets.HOST_IP != '' }}"
          echo "SERVER_HOST exists: ${{ secrets.SERVER_HOST != '' }}"
          echo "SSH_USER exists: ${{ secrets.SSH_USER != '' }}"
          echo "DROPLET_SSH_KEY exists: ${{ secrets.DROPLET_SSH_KEY != '' }}"

      - name: Sync latest changes on ${{ inputs.environment }} server
        uses: appleboy/ssh-action@v1.1.0
        env:
          REPO_DIR_PATH: ${{ env.REPO_DIR_PATH }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: REPO_DIR_PATH
          script: |
            cd "$REPO_DIR_PATH"
            git config --global --add safe.directory "$REPO_DIR_PATH"
            git pull origin main || git pull origin master

      - name: Restart Docker Compose on ${{ inputs.environment }} server
        uses: appleboy/ssh-action@v1.1.0
        env:
          REPO_DIR_PATH: ${{ env.REPO_DIR_PATH }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: REPO_DIR_PATH
          script: |
            cd "$REPO_DIR_PATH"
            docker-compose -f docker-compose.envsubst.yaml down
            rm docker-compose.envsubst.yaml || true
            export TAILSCALE_IP="$(tailscale ip --4)"
            envsubst < docker-compose.yaml > docker-compose.envsubst.yaml
            docker-compose -f docker-compose.envsubst.yaml up -d --build --force-recreate

      - name: Wait for ${{ inputs.environment }} server
        timeout-minutes: 3
        run: |
          echo "Waiting for ${{ inputs.environment }} server..."
          timeout=180
          while ! curl -s http://${{ secrets.SERVER_HOST }}:443/get_sound_series > /dev/null; do
            sleep 1
            timeout=$((timeout-1))
            if [ "$timeout" -le 0 ]; then
              echo "Timed out waiting for server to respond."
              exit 1
            fi
          done
          echo "${{ inputs.environment }} server is up." 