name: Deploy secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy secrets to"
        required: true
        type: choice
        options:
          - stage
          - prod
      restart-containers:
        description: 'Restarting containers to reload secrets'
        required: false
        default: 'true'
      vm_host_address:
        description: 'IP address of the VM'
        required: false
        default: ""

jobs:
  deploy-secrets:
    uses: ./.github/workflows/deploy-secrets.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      restart-containers: ${{ github.event.inputs.restart-containers }}
      vm_host_address: ${{ github.event.inputs.vm_host_address }}
    secrets: inherit 
