name: Deploy new version

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - prod

jobs:
  deploy-stage:
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: stage
    secrets: inherit

  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit
