name: Deploy secrets

on:
  workflow_dispatch:
    inputs:
      restart-containers:
        description: 'Restarting containers to reload secrets'
        required: false
        default: 'true'
      vm_ip:
        description: 'IP address of the VM'
        required: false
        default: ""

env:
  REPO_DIR_PATH: /home/user/niyya

jobs:
  deploy-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [server]
    environment: ${{ matrix.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Read and Substitute Environment Variables
      run: |
        pwd
        ls -la ${{ matrix.environment }}
        # Read the example env file and substitute values
        echo '${{ toJSON(secrets) }}' > secrets.json
        cat secrets.json

        echo "Reading and substituting environment variables..."
        cat ${{ matrix.environment }}/.env.example

        while IFS='=' read -r key value || [ -n "$key" ]; do
          # Remove leading and trailing spaces
          key=$(echo $key | xargs)
          
          # Check if the key is not empty and doesn't start with a comment
          if [[ ! -z "$key" && ! $key =~ ^# ]]; then
            # Get the corresponding secret value from the JSON file
            secret_value=$(jq -r --arg key "$key" '.[$key]' secrets.json)
            
            # Debug output
            echo "Processing key: $key"
            echo "Original value: $value"
            echo "Secret value: $secret_value"
            
            # If the secret exists, substitute it in the .env file
            if [[ ! -z "$secret_value" && "$secret_value" != "null" ]]; then
              echo "$key=$secret_value" >> ${{ matrix.environment }}/.env
            else
              echo "$key=$value" >> ${{ matrix.environment }}/.env
            fi
          fi
        done < ${{ matrix.environment }}/.env.example

        echo "Resulting .env file:"
        cat ${{ matrix.environment }}/.env

    - name: Upload .env to server
      run: |
        VM_IP=${{ inputs.vm_ip || secrets.HOST_IP }}
        scp -o StrictHostKeyChecking=no ${{ matrix.environment }}/.env ${{ secrets.SSH_USER }}@$VM_IP:${{ env.REPO_DIR_PATH }}/${{ matrix.environment }}/.env

  restart-containers:
    runs-on: ubuntu-latest
    needs: deploy-secrets
    if: inputs.restart-containers == 'true'
    steps:
    - name: Stop and rerun Docker Compose
      uses: appleboy/ssh-action@v1.1.0
      env:
        REPO_DIR_PATH: ${{ env.REPO_DIR_PATH }}
      with:
        host: ${{ inputs.vm_ip || secrets.HOST_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        port: 22
        envs: REPO_DIR_PATH
        script: |
          cd "$REPO_DIR_PATH"
          docker-compose down
          docker-compose up -d --build --force-recreate 